Repository amberframework/amber, pull requests merged in 2018-03, with the labels that each got.

#702 Add StackOverflow tag: amber-framework
  README.md
Labels: pr:needs-review, pr:wip

#649 add toGranite() to Date prototype
  src/amber/cli/templates/app/src/assets/javascripts/main.js
Labels: status:discussion

#703 fix support for fetch_all in form params
  spec/amber/router/params_spec.cr
  src/amber/router/params.cr
Labels: pr:wip

#700 [Router] Adds OPTIONS and HEAD routes by default
  spec/amber/router/route_spec.cr
  spec/amber/router/router_spec.cr
  src/amber/dsl/router.cr
  src/amber/router/route.cr
  src/amber/router/router.cr
Labels: pr:wip

#706 [Specs] Adds/Cleans up Params Specs
  spec/amber/validations/params_spec.cr
Labels: pr:needs-review

#689 [CLI] Add a command to open db connection.
  src/amber/cli/commands/database.cr
Labels: pr:needs-review

#719 Add missing attribute
  assets/js/amber.js
  assets/js/amber.min.js
  src/amber/cli/templates/app/public/dist/main.bundle.js
Labels: pr:needs-review
