Repository amberframework/amber, pull requests merged in 2018-05, with the labels that each got.

#771 Changed visibility scope of some Amber::Server methods
  src/amber/server/server.cr
Labels: kind:enhancement

#777 Use break instead of exit in Amber::Server#start
  src/amber/server/server.cr
Labels: kind:enhancement, pr:needs-review

#779 Fix Auth generator for classes different than User
  src/amber/cli/templates/auth/src/models/{{name}}.cr.ecr
Labels: kind:enhancement, pr:needs-review

#780 Fix indentation when adding auth routes
  src/amber/cli/helpers/helpers.cr
  src/amber/cli/templates/auth.cr
Labels: kind:enhancement, pr:needs-review

#782 Fix HTML issues in application.ecr template
  src/amber/cli/templates/app/src/views/layouts/application.ecr.ecr
Labels: kind:bug, pr:needs-review

#788 Update redis to latest version
  shard.yml
Labels: kind:enhancement, pr:needs-review

#746 Update default bootstrap version to 4 (latest cdn)
  spec/support/fixtures/render_fixtures.cr
  spec/support/sample/views/test/_form.slang
  src/amber/cli/templates/app/src/assets/stylesheets/main.scss
  src/amber/cli/templates/app/src/views/home/index.ecr.ecr
  src/amber/cli/templates/app/src/views/home/index.slang.ecr
  src/amber/cli/templates/app/src/views/layouts/application.ecr.ecr
  src/amber/cli/templates/app/src/views/layouts/application.slang.ecr
  src/amber/cli/templates/auth/src/views/layouts/+_nav.ecr.ecr
  src/amber/cli/templates/auth/src/views/layouts/+_nav.slang.ecr
  src/amber/cli/templates/auth/src/views/registration/new.ecr.ecr
  src/amber/cli/templates/auth/src/views/registration/new.slang.ecr
  src/amber/cli/templates/auth/src/views/session/new.ecr.ecr
  src/amber/cli/templates/auth/src/views/session/new.slang.ecr
  src/amber/cli/templates/auth/src/views/{{name}}/edit.ecr.ecr
  src/amber/cli/templates/auth/src/views/{{name}}/edit.slang.ecr
  src/amber/cli/templates/auth/src/views/{{name}}/show.ecr.ecr
  src/amber/cli/templates/auth/src/views/{{name}}/show.slang.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/_form.ecr.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/_form.slang.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/index.ecr.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/index.slang.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/show.ecr.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/show.slang.ecr
Labels: pr:needs-review

#789 Update granite and rename Granite::ORM to Granite
  spec/support/fixtures/cli_fixtures.cr
  src/amber/cli/templates/app/config/initializers/database.cr.ecr
  src/amber/cli/templates/app/shard.yml.ecr
  src/amber/cli/templates/app/spec/spec_helper.cr
  src/amber/cli/templates/auth/src/models/{{name}}.cr.ecr
  src/amber/cli/templates/model/granite/src/models/{{name}}.cr.ecr
Labels: kind:enhancement, pr:needs-review

#795 Fixes Crecto
  src/amber/cli/templates/app/config/initializers/database.cr.ecr
  src/amber/cli/templates/scaffold/controller/crecto/src/controllers/{{name}}_controller.cr.ecr
Labels: kind:bug, pr:needs-review

#798 Fix format issues when scaffolding auth
  src/amber/cli/helpers/helpers.cr
  src/amber/cli/templates/auth.cr
  src/amber/cli/templates/auth/src/controllers/session_controller.cr.ecr
  src/amber/cli/templates/auth/src/controllers/{{name}}_controller.cr.ecr
  src/amber/cli/templates/auth/src/models/{{name}}.cr.ecr
  src/amber/cli/templates/auth/src/pipes/authenticate.cr.ecr
Labels: kind:enhancement, pr:needs-review

#791 Simplifies render by removing edge case.
  spec/support/fixtures/controller_fixtures.cr
  spec/support/sample/views/layouts/layout_with_partials.slang
  src/amber/controller/helpers/render.cr
Labels: kind:enhancement, pr:needs-review

#813 Fix broken links on amber README
  README.md
Labels: kind:documentation, kind:enhancement, pr:needs-review

#797 Fix crystal tool format when creating a new app
  spec/build_spec.cr
  src/amber/cli/templates/app/config/application.cr.ecr
  src/amber/cli/templates/app/config/initializers/database.cr.ecr
  src/amber/cli/templates/app/src/controllers/home_controller.cr.ecr
  src/amber/cli/templates/mailer/src/mailers/{{name}}_mailer.cr.ecr
  src/amber/cli/templates/model/granite/src/models/{{name}}.cr.ecr
  src/amber/cli/templates/socket/src/sockets/{{name}}_socket.cr.ecr
Labels: kind:enhancement, pr:needs-review

#812 README Template: simple, better, and enjoyable.
  src/amber/cli/templates/app/README.md.ecr
Labels: kind:enhancement, pr:needs-review

#786 Ameba v0.5.0 -> v0.6.0
  shard.yml
  spec/amber/amber_spec.cr
  spec/amber/cli/commands/generator_spec.cr
  spec/amber/cli/commands/init_spec.cr
  spec/amber/cli/recipes/recipe_fetcher_spec.cr
  spec/amber/controller/redirect_spec.cr
  spec/amber/dsl/server_spec.cr
  spec/amber/pipes/error_spec.cr
  spec/amber/router/params_spec.cr
  spec/amber/router/request_spec.cr
  spec/amber/router/route_spec.cr
  spec/amber/router/router_spec.cr
  spec/amber/validations/base_rule_spec.cr
  spec/amber/validations/params_spec.cr
  spec/amber/websockets/channel_spec.cr
  spec/amber/websockets/client_socket_spec.cr
  spec/amber/websockets/client_sockets_spec.cr
  spec/support/helpers/cli_helper.cr
  spec/support/helpers/router_helper.cr
  src/amber/cli/recipes/controller.cr
  src/amber/cli/templates/app/config/routes.cr
  src/amber/cli/templates/controller.cr
  src/amber/router/cookies.cr
  src/amber/router/router.cr
  src/amber/websockets/adapters/redis.cr
  src/amber/websockets/client_socket.cr
  src/amber/websockets/client_sockets.cr
Labels: kind:enhancement, pr:needs-review

#784 Fix exec exit status code
  src/amber/cli/commands/exec.cr
Labels: kind:bug, pr:needs-review

#796 Change confusing puts to info and add error logger
  src/amber/cli/command.cr
  src/amber/cli/commands/database.cr
  src/amber/cli/commands/exec.cr
  src/amber/cli/commands/generate.cr
  src/amber/cli/commands/new.cr
  src/amber/cli/commands/pipelines.cr
  src/amber/cli/commands/routes.cr
  src/amber/cli/recipes/recipe.cr
  src/amber/cli/templates/template.cr
Labels: kind:enhancement, pr:needs-review

#803 fixes blocking cors issues
  spec/amber/pipes/cors_spec.cr
  src/amber/pipes/cors.cr
Labels: kind:bug, pr:needs-review

#804 fixes not_nil runtime exception in json parser
  spec/amber/router/parsers/json_spec.cr
  src/amber/router/parsers/json.cr
Labels: kind:enhancement, pr:needs-review

#814 Use context.locale instead of ::I18n.locale
  src/amber/cli/templates/app/shard.yml.ecr
  src/amber/controller/helpers/i18n.cr
Labels: kind:bug, kind:enhancement, pr:needs-review

#764 [CLI] change the default recipe source URL
  spec/amber/cli/recipes/recipe_fetcher_spec.cr
  spec/amber/cli/recipes/recipe_spec.cr
  src/amber/cli/recipes/recipe_fetcher.cr
Labels: kind:enhancement, pr:needs-review

#821 Update ::puts to puts
  src/amber/cli/commands/exec.cr
Labels: kind:enhancement, pr:needs-review

#774 Support Procs in respond_with
  spec/amber/controller/respond_with_spec.cr
  spec/support/fixtures/controller_fixtures.cr
  src/amber/controller/helpers/redirect.cr
  src/amber/controller/helpers/responders.cr
Labels: kind:enhancement, pr:needs-review

#832 fix CORS issue when multiple origins
  spec/amber/pipes/cors_spec.cr
  src/amber/pipes/cors.cr
Labels: kind:enhancement, pr:needs-review
