Repository amberframework/amber, pull requests merged in 2018-04, with the labels that each got.

#726 Small style enhancement for buttons color
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/index.ecr.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/index.slang.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/show.ecr.ecr
  src/amber/cli/templates/scaffold/view/src/views/{{name}}/show.slang.ecr
Labels: pr:needs-review

#728 [CLI] add support for Recipes (squashed commits)
  shard.yml
  spec/amber/cli/commands/init_spec.cr
  spec/amber/cli/recipes/recipe_fetcher_spec.cr
  spec/amber/cli/recipes/recipe_spec.cr
  spec/support/helpers/cli_helper.cr
  src/amber/cli/commands.cr
  src/amber/cli/commands/generate.cr
  src/amber/cli/commands/new.cr
  src/amber/cli/config.cr
  src/amber/cli/recipes/app.cr
  src/amber/cli/recipes/controller.cr
  src/amber/cli/recipes/file_entries.cr
  src/amber/cli/recipes/filters.cr
  src/amber/cli/recipes/model.cr
  src/amber/cli/recipes/recipe.cr
  src/amber/cli/recipes/recipe_fetcher.cr
  src/amber/cli/recipes/scaffold/controller.cr
  src/amber/cli/recipes/scaffold/view.cr
  src/amber/cli/templates/field.cr
Labels: kind:feature, pr:needs-review

#735 Add StackOverflow advice
  .github/issue_template.md
Labels: pr:needs-review

#736 [Fix] Corrects indentation and adds new line
  shard.yml
Labels: pr:needs-review, status:on-hold

#734 Small README adjustments
  README.md
Labels: pr:needs-review

#743 Remove temporary filters
  src/amber/cli/recipes/filters.cr
  src/amber/cli/recipes/recipe.cr
Labels: kind:enhancement, pr:needs-review

#740 [CI] Attempts to fix Build Spec For Consistency
  .travis.yml
  spec/build_spec.cr
Labels: kind:optimization

#741 Change liquid.cr commit by latest version
  shard.yml
Labels: pr:needs-review

#732 Improve column names in `amber pipelines`
  spec/amber/cli/commands/pipelines/pipelines_spec.cr
  src/amber/cli/commands/pipelines.cr
Labels: kind:enhancement, pr:needs-review
