Repository amberframework/amber, pull requests merged in 2018-06, with the labels that each got.

#837 Fix crecto controller spec
  src/amber/cli/templates/scaffold/controller/crecto/spec/controllers/{{name}}_controller_spec.cr.ecr
Labels: kind:enhancement, pr:needs-review

#845 Fix amber framework badge
  README.md
Labels: kind:enhancement, pr:needs-review

#844 Updates dependency badge
  README.md
Labels: kind:documentation, pr:needs-review

#824 Fix Crecto auth spec
  src/amber/cli/templates/auth/crecto/spec/models/{{name}}_spec.cr.ecr
Labels: kind:bug, pr:needs-review

#818 Add missing migrations generator
  src/amber/cli/recipes/recipe.cr
Labels: kind:cli, pr:needs-review

#823 Fixes view filename for controller in recipes
  src/amber/cli/recipes/controller.cr
Labels: kind:bug, pr:needs-review

#830 Add missing status codes to logs
  src/amber/pipes/logger.cr
Labels: kind:enhancement, pr:needs-review

#820 Print spec_result just once
  spec/build_spec.cr
Labels: kind:enhancement, pr:needs-review

#828 api generator
  src/amber/cli/commands/generate.cr
  src/amber/cli/templates/api/controller.cr
  src/amber/cli/templates/api/controller/crecto/spec/controllers/spec_helper.cr
  src/amber/cli/templates/api/controller/crecto/spec/controllers/{{name}}_controller_spec.cr.ecr
  src/amber/cli/templates/api/controller/crecto/src/controllers/{{name}}_controller.cr.ecr
  src/amber/cli/templates/api/controller/granite/spec/controllers/spec_helper.cr
  src/amber/cli/templates/api/controller/granite/spec/controllers/{{name}}_controller_spec.cr.ecr
  src/amber/cli/templates/api/controller/granite/src/controllers/{{name}}_controller.cr.ecr
  src/amber/cli/templates/api/crecto_controller.cr
  src/amber/cli/templates/api/granite_controller.cr
  src/amber/cli/templates/app/config/routes.cr
  src/amber/cli/templates/template.cr
Labels: kind:cli, kind:enhancement, pr:needs-review

#825 Update assets
  assets/js/amber.min.js
  package.json
  src/amber/cli/templates/app/package.json.ecr
  src/amber/cli/templates/app/public/dist/main.bundle.css
  src/amber/cli/templates/app/public/dist/main.bundle.js
Labels: kind:enhancement, pr:needs-review

#822 Update Redis
  shard.yml
Labels: kind:enhancement, pr:needs-review

#857 Update to Crystal/0.25.0
  .ameba.yml
  Dockerfile
  shard.yml
  spec/amber/cli/commands/database_spec.cr
  spec/amber/cli/commands/routes/routes_spec.cr
  spec/amber/pipes/reload_spec.cr
  spec/amber/router/cookies_spec.cr
  spec/amber/router/params_spec.cr
  spec/amber/router/parsers/json_spec.cr
  spec/amber/router/session/cookie_store_spec.cr
  spec/amber/router/session/redis_store_spec.cr
  spec/support/helpers/validations_helper.cr
  spec/support/helpers/websockets_helper.cr
  src/amber/cli/helpers/process_runner.cr
  src/amber/cli/recipes/file_entries.cr
  src/amber/cli/templates/app/shard.yml.ecr
  src/amber/cli/templates/auth/granite/src/controllers/session_controller.cr.ecr
  src/amber/cli/templates/auth/granite/src/models/{{name}}.cr.ecr
  src/amber/environment/logger_builder.cr
  src/amber/pipes/static.cr
  src/amber/router/flash.cr
  src/amber/router/params.cr
  src/amber/router/parsers/json.cr
  src/amber/router/session/cookie_store.cr
  src/amber/router/session/redis_store.cr
  src/amber/server/server.cr
  src/amber/support/client_reload.cr
  src/amber/support/mime_types.cr
  src/amber/validators/params.cr
Labels: kind:breaking-change

#816 Remove Granite.settings.logger from spec
  src/amber/cli/templates/app/spec/spec_helper.cr.ecr
Labels: kind:bug, kind:database, kind:enhancement, pr:needs-review

#874 Add shards check
  spec/build_spec.cr
Labels: kind:enhancement, pr:needs-review

#880 Update mysql and sqlite dependencies (v0.25.0 compat)
  shard.yml
  src/amber/cli/templates/app/shard.yml.ecr
Labels: kind:database, pr:needs-review

#878 Update Crecto to v0.9.0 (v0.25.0 compat)
  src/amber/cli/templates/app/shard.yml.ecr
Labels: kind:database, pr:needs-review

#882 Update crystal-redis to 2.0.0
  shard.yml
Labels: kind:enhancement

#868 Fixes home page on small screens
  src/amber/cli/templates/app/src/views/home/index.ecr.ecr
  src/amber/cli/templates/app/src/views/home/index.slang.ecr
Labels: kind:enhancement, pr:needs-review

#860 Remove reload pipe
  spec/amber/cli/commands/pipelines/pipelines_spec.cr
  src/amber/cli/templates/app/config/routes.cr
  src/amber/pipes/reload.cr
Labels: kind:enhancement, kind:feature, pr:needs-review

#863 Add favicon on html pages with default layout
  src/amber/cli/templates/app/public/favicon.ico
  src/amber/cli/templates/app/public/favicon.png
  src/amber/cli/templates/app/src/views/layouts/application.ecr.ecr
  src/amber/cli/templates/app/src/views/layouts/application.slang.ecr
Labels: kind:enhancement, kind:feature, pr:needs-review

#849 [Bug] Redirect With Controller as String
  spec/amber/controller/redirect_spec.cr
  src/amber/controller/helpers/redirect.cr
Labels: kind:bug, pr:needs-review

#883 [Cleanup] Removes unnecessary code from spec helper
  src/amber/cli/templates/app/spec/spec_helper.cr.ecr
Labels: kind:enhancement, pr:needs-review

#862 Removes support for amber deploy
  src/amber/cli/commands/deploy.cr
Labels: kind:breaking-change, kind:cli, kind:feature, pr:needs-review

#886 Disables granite logging in specs
  src/amber/cli/templates/app/spec/spec_helper.cr.ecr
Labels: kind:bug, pr:needs-review

#852 [Cleanup] Cleans Controller Scaffold
  spec/amber/cli/recipes/recipe_fetcher_spec.cr
  spec/amber/controller/respond_with_spec.cr
  spec/support/fixtures/controller_fixtures.cr
  src/amber/cli/commands/database.cr
  src/amber/cli/recipes/recipe_fetcher.cr
  src/amber/cli/templates/scaffold/controller/crecto/src/controllers/{{name}}_controller.cr.ecr
  src/amber/cli/templates/scaffold/controller/granite/src/controllers/{{name}}_controller.cr.ecr
  src/amber/controller/helpers/redirect.cr
  src/amber/controller/helpers/responders.cr
  src/amber/controller/helpers/route.cr
Labels: kind:enhancement, pr:needs-review

#889 Removes .not_nil! from Crecto Template
  src/amber/cli/templates/scaffold/controller/crecto/src/controllers/{{name}}_controller.cr.ecr
Labels: kind:enhancement

#888 [Spec] Removes Extra Build Spec
  spec/build_spec.cr
Labels: kind:enhancement

#893 Using non-parenthesis method calls in scaffolded controllers
  src/amber/cli/templates/scaffold/controller/crecto/src/controllers/{{name}}_controller.cr.ecr
  src/amber/cli/templates/scaffold/controller/granite/src/controllers/{{name}}_controller.cr.ecr
Labels: kind:enhancement, pr:needs-review

#894 Closing the container div for application.ecr template.
  src/amber/cli/templates/app/src/views/layouts/application.ecr.ecr
Labels: kind:bug

#898 [Responders] Overloads json method
  src/amber/controller/helpers/responders.cr
Labels: kind:enhancement, pr:needs-review

#897 Added support for returning a default value while using flash
  spec/amber/pipes/flash_spec.cr
  src/amber/router/flash.cr
Labels: kind:enhancement, kind:feature
