Repository amberframework/amber, pull requests merged in 2019-01, with the labels that each got.

#1024 Break up the cookies classes
  src/amber/router/cookies.cr
  src/amber/router/cookies/abstract_store.cr
  src/amber/router/cookies/encrypted_store.cr
  src/amber/router/cookies/permanent_store.cr
  src/amber/router/cookies/signed_store.cr
  src/amber/router/cookies/store.cr
Labels: pr:needs-review

#1028 Prefer JavaScript UMD modules spec
  assets/js/amber.js
  assets/js/amber.min.js
  package.json
Labels: pr:needs-review

#1025 Only output exception message to log, not entire html response
  src/amber/pipes/error.cr
Labels: pr:needs-review

#1021 Don't present optional param if not present input params
  spec/amber/validations/params_spec.cr
  src/amber/router/params.cr
  src/amber/validators/params.cr
Labels: pr:wip

#1048 Makes settings.secrets usable for end users.
  spec/amber/environment/settings_spec.cr
  src/amber/environment/settings.cr
Labels: kind:enhancement

#1037 Treat mailer as first class citizen in new app
  src/amber/cli/generators/mailer.cr
  src/amber/cli/templates/app/config/application.cr.ecr
  src/amber/cli/templates/app/config/initializers/mailer.cr
  src/amber/cli/templates/app/src/mailers/application_mailer.cr.ecr
  src/amber/cli/templates/app/src/views/layouts/mailer.ecr.ecr
  src/amber/cli/templates/app/src/views/layouts/mailer.slang
  src/amber/cli/templates/mailer/config/initializers/mailer.cr.ecr
Labels: kind:enhancement, kind:feature

#1043 Add method `Amber::Validators::Params#to_unsafe_h`
  spec/amber/validations/params_spec.cr
  src/amber/validators/params.cr
Labels: kind:feature
